name: my-first-workflow
on: workflow_dispatch
jobs:
  firstjoB:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world"
      - name: Print Goodbye
        run: echo "Good Bye!"
